# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thanks.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ThanksDialog(object):
    def setupUi(self, ThanksDialog):
        ThanksDialog.setObjectName("ThanksDialog")
        ThanksDialog.resize(840, 618)
        ThanksDialog.setMouseTracking(False)
        self.L1 = QtWidgets.QLabel(ThanksDialog)
        self.L1.setGeometry(QtCore.QRect(280, 10, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(10)
        self.L1.setFont(font)
        self.L1.setStyleSheet("color:rgb(243, 243, 243);font: 87 italic 11pt \"Segoe UI Black\";\n"
"font: 87 italic 26pt \"Segoe UI Black\";\n"
"")
        self.L1.setObjectName("L1")
        self.L6 = QtWidgets.QLabel(ThanksDialog)
        self.L6.setGeometry(QtCore.QRect(50, 570, 151, 41))
        self.L6.setStyleSheet("color:rgb(243, 243, 243);font: 87 italic 11pt \"Segoe UI Black\";\n"
"font: 75 10pt \"Perpetua Titling MT\";\n"
"font: 75 italic 12pt \"Verdana\";\n"
"")
        self.L6.setObjectName("L6")
        self.label = QtWidgets.QLabel(ThanksDialog)
        self.label.setGeometry(QtCore.QRect(310, 570, 261, 41))
        self.label.setStyleSheet("color:rgb(243, 243, 243);font: 87 italic 11pt \"Segoe UI Black\";\n"
"font: 75 10pt \"Perpetua Titling MT\";\n"
"font: 75 italic 12pt \"Verdana\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ThanksDialog)
        self.label_2.setGeometry(QtCore.QRect(650, 580, 181, 20))
        self.label_2.setStyleSheet("color:rgb(243, 243, 243);font: 87 italic 11pt \"Segoe UI Black\";\n"
"font: 75 10pt \"Perpetua Titling MT\";\n"
"font: 75 italic 12pt \"Verdana\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ThanksDialog)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 841, 571))
        self.label_3.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("WhatsApp Image 2023-10-23 at 15.35.33_7aeecbb9.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ThanksDialog)
        self.label_4.setGeometry(QtCore.QRect(620, 580, 21, 21))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Downloads/icons8-call-50.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(ThanksDialog)
        self.label_5.setGeometry(QtCore.QRect(20, 580, 21, 20))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../Downloads/2227-removebg-preview.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(ThanksDialog)
        self.label_6.setGeometry(QtCore.QRect(-6, 566, 851, 61))
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.go_back_button = QtWidgets.QPushButton(ThanksDialog)
        self.go_back_button.setGeometry(QtCore.QRect(370, 490, 141, 41))
        self.go_back_button.setStyleSheet("font: 75 12pt  \"Segoe UI Semibold\";\n"
"color:;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 184, 62);")
        self.go_back_button.setObjectName("go_back_button")
        self.label_7 = QtWidgets.QLabel(ThanksDialog)
        self.label_7.setGeometry(QtCore.QRect(30, 80, 281, 71))
        self.label_7.setStyleSheet("font: 75 25pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(ThanksDialog)
        self.label_8.setGeometry(QtCore.QRect(90, 140, 391, 71))
        self.label_8.setStyleSheet("font: 75 25pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(ThanksDialog)
        self.label_9.setGeometry(QtCore.QRect(20, 260, 441, 51))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(ThanksDialog)
        self.label_10.setGeometry(QtCore.QRect(130, 320, 161, 131))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../resources/emoticon (3).png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_3.raise_()
        self.label_6.raise_()
        self.L1.raise_()
        self.L6.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.go_back_button.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()

        self.retranslateUi(ThanksDialog)
        QtCore.QMetaObject.connectSlotsByName(ThanksDialog)

    def retranslateUi(self, ThanksDialog):
        _translate = QtCore.QCoreApplication.translate
        ThanksDialog.setWindowTitle(_translate("ThanksDialog", "Dialog"))
        self.L1.setText(_translate("ThanksDialog", "Greek Burger"))
        self.L6.setText(_translate("ThanksDialog", "@greekburger__"))
        self.label.setText(_translate("ThanksDialog", "greekburger@gmail.com"))
        self.label_2.setText(_translate("ThanksDialog", "09054382094"))
        self.go_back_button.setText(_translate("ThanksDialog", "Homepage"))
        self.label_7.setText(_translate("ThanksDialog", "Thank you"))
        self.label_8.setText(_translate("ThanksDialog", "For your Patronage"))
        self.label_9.setText(_translate("ThanksDialog", "We hope to see your order again😊😊😊"))
