# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'receipt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReceiptDialog(object):
    def setupUi(self, ReceiptDialog):
        ReceiptDialog.setObjectName("ReceiptDialog")
        ReceiptDialog.resize(485, 624)
        self.label = QtWidgets.QLabel(ReceiptDialog)
        self.label.setGeometry(QtCore.QRect(150, 40, 271, 61))
        self.label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ReceiptDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 461, 51))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ReceiptDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 461, 51))
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ReceiptDialog)
        self.label_4.setGeometry(QtCore.QRect(-10, 0, 101, 71))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Downloads/007d85591e9ea14e737977be9345dfe3.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(ReceiptDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 290, 461, 41))
        self.label_5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.ok_button = QtWidgets.QPushButton(ReceiptDialog)
        self.ok_button.setGeometry(QtCore.QRect(380, 580, 93, 28))
        self.ok_button.setObjectName("ok_button")
        self.label_6 = QtWidgets.QLabel(ReceiptDialog)
        self.label_6.setGeometry(QtCore.QRect(10, 360, 461, 41))
        self.label_6.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(ReceiptDialog)
        self.label_8.setGeometry(QtCore.QRect(60, 450, 321, 21))
        self.label_8.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(ReceiptDialog)
        self.label_9.setGeometry(QtCore.QRect(100, 0, 381, 71))
        self.label_9.setStyleSheet("font: 87 25pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(ReceiptDialog)
        self.label_7.setGeometry(QtCore.QRect(170, 110, 241, 41))
        self.label_7.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(ReceiptDialog)
        self.label_10.setGeometry(QtCore.QRect(-6, -5, 501, 641))
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_10.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.ok_button.raise_()
        self.label_6.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_7.raise_()

        self.retranslateUi(ReceiptDialog)
        QtCore.QMetaObject.connectSlotsByName(ReceiptDialog)

    def retranslateUi(self, ReceiptDialog):
        _translate = QtCore.QCoreApplication.translate
        ReceiptDialog.setWindowTitle(_translate("ReceiptDialog", "Dialog"))
        self.label.setText(_translate("ReceiptDialog", "Payment Receipt"))
        self.label_2.setText(_translate("ReceiptDialog", "Total Amount: ₦"))
        self.label_3.setText(_translate("ReceiptDialog", "Shipping Address:"))
        self.label_5.setText(_translate("ReceiptDialog", "City:"))
        self.ok_button.setText(_translate("ReceiptDialog", "OK"))
        self.label_6.setText(_translate("ReceiptDialog", "State:"))
        self.label_8.setText(_translate("ReceiptDialog", "             Thank you for your patronage"))
        self.label_9.setText(_translate("ReceiptDialog", "GREEK BURGER"))
        self.label_7.setText(_translate("ReceiptDialog", "Payment Successful"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReceiptDialog = QtWidgets.QDialog()
    ui = Ui_ReceiptDialog()
    ui.setupUi(ReceiptDialog)
    ReceiptDialog.show()
    sys.exit(app.exec_())
