# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 624)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 851, 591))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 60, 301, 81))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"font: 87 25pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(310, 120, 441, 81))
        self.label.setStyleSheet("font: 75 36pt \"MS Shell Dlg 2\";\n"
"background-color: none;\n"
"color: rgb(255, 224, 49);")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 261, 181))
        self.label_3.setStyleSheet("filter: blur(20px);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Downloads/ultimate-burger-with-crispy-onion-rings-chips.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(290, 220, 261, 181))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Downloads/1628854161-burgertoppingshero.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(560, 220, 261, 181))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../Downloads/Moist-Chicken-Burgers-1180x580.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 121, 71))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../../Downloads/[removal.ai]_0e8a4621-ccee-4b11-891e-84fab94a39a6_007d85591e9ea14e737977be9345dfe3.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(130, 450, 381, 51))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.order_now_button = QtWidgets.QPushButton(self.frame)
        self.order_now_button.setGeometry(QtCore.QRect(520, 460, 131, 31))
        self.order_now_button.setStyleSheet("font: 75 12pt  \"Segoe UI Semibold\";\n"
"color:;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 184, 62);")
        self.order_now_button.setObjectName("order_now_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 26))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        # self.menuMenu = QtWidgets.QMenu(self.menubar)
        # self.menuMenu.setObjectName("menuMenu")
        # self.menuReview = QtWidgets.QMenu(self.menubar)
        # self.menuReview.setObjectName("menuReview")
        # self.menuContact = QtWidgets.QMenu(self.menubar)
        # self.menuContact.setObjectName("menuContact")
        # self.menuContact_2 = QtWidgets.QMenu(self.menubar)
        # self.menuContact_2.setObjectName("menuContact_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHome.menuAction())
        # self.menubar.addAction(self.menuMenu.menuAction())
        # self.menubar.addAction(self.menuReview.menuAction())
        # self.menubar.addAction(self.menuContact.menuAction())
        # self.menubar.addAction(self.menuContact_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Welcome To"))
        self.label.setText(_translate("MainWindow", "GREEK BURGER "))
        self.label_7.setText(_translate("MainWindow", "Grab a burger today for a satisfying meal"))
        self.order_now_button.setText(_translate("MainWindow", "ORDER NOW"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
        # self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        # self.menuReview.setTitle(_translate("MainWindow", "Review"))
        # self.menuContact.setTitle(_translate("MainWindow", "About"))
        # self.menuContact_2.setTitle(_translate("MainWindow", "Contact"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
