# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(842, 622)
        self.L1 = QtWidgets.QLabel(Dialog)
        self.L1.setGeometry(QtCore.QRect(220, 20, 411, 61))
        self.L1.setStyleSheet("color: rgb(255, 224, 49);\n"
"font: 87 30pt \"Arial Black\";\n"
"")
        self.L1.setObjectName("L1")
        self.take_order_button = QtWidgets.QPushButton(Dialog)
        self.take_order_button.setGeometry(QtCore.QRect(310, 550, 171, 41))
        self.take_order_button.setStyleSheet("font: 75 13pt \"Arial\";\n"
"background-color: rgb(254, 255, 203);\n"
"boder: none;\n"
"\n"
"")
        self.take_order_button.setObjectName("take_order_button")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(490, 410, 251, 137))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.P3 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.P3.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.P3.setObjectName("P3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.P3)
        self.P2_2 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.P2_2.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.P2_2.setObjectName("P2_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.P2_2)
        self.L13 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.L13.setObjectName("L13")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.L13)
        self.L14 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.L14.setObjectName("L14")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.L14)
        self.L15 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.L15.setObjectName("L15")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.L15)
        self.P4 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.P4.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.P4.setObjectName("P4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.P4)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 131, 40))
        self.label_2.setStyleSheet("color:rgb(243, 243, 243);font: 87 italic 11pt \"Segoe UI Black\";\n"
"font: 87 italic 22pt \"Segoe UI Black\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.L2 = QtWidgets.QLabel(Dialog)
        self.L2.setGeometry(QtCore.QRect(350, 100, 111, 41))
        self.L2.setStyleSheet("color:rgb(243, 243, 243);font: 87 italic 11pt \"Segoe UI Black\";\n"
"font: 87 italic 22pt \"Segoe UI Black\";\n"
"")
        self.L2.setObjectName("L2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(120, 360, 121, 31))
        self.label_4.setStyleSheet("color:rgb(243, 243, 243);font: 87 italic 11pt \"Segoe UI Black\";\n"
"font: 87 italic 22pt \"Segoe UI Black\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 400, 251, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.L7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.L7.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.L7.setObjectName("L7")
        self.gridLayout.addWidget(self.L7, 1, 2, 1, 1)
        self.L8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.L8.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.L8.setObjectName("L8")
        self.gridLayout.addWidget(self.L8, 2, 2, 1, 1)
        self.S6 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.S6.setObjectName("S6")
        self.gridLayout.addWidget(self.S6, 0, 3, 1, 1)
        self.S8 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.S8.setObjectName("S8")
        self.gridLayout.addWidget(self.S8, 2, 3, 1, 1)
        self.S7 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.S7.setObjectName("S7")
        self.gridLayout.addWidget(self.S7, 1, 3, 1, 1)
        self.L6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.L6.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.L6.setObjectName("L6")
        self.gridLayout.addWidget(self.L6, 0, 2, 1, 1)
        self.C6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.C6.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.C6.setObjectName("C6")
        self.gridLayout.addWidget(self.C6, 0, 0, 1, 1)
        self.C7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.C7.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.C7.setObjectName("C7")
        self.gridLayout.addWidget(self.C7, 1, 0, 1, 1)
        self.C8 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.C8.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.C8.setObjectName("C8")
        self.gridLayout.addWidget(self.C8, 2, 0, 1, 1)
        self.B2 = QtWidgets.QPushButton(Dialog)
        self.B2.setGeometry(QtCore.QRect(640, 360, 91, 31))
        self.B2.setStyleSheet("font: 75 13pt \"Arial\";\n"
"background-color: rgb(254, 255, 203);\n"
"boder: none;\n"
"\n"
"")
        self.B2.setObjectName("B2")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(40, 170, 301, 181))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.C4 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.C4.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.C4.setObjectName("C4")
        self.gridLayout_4.addWidget(self.C4, 5, 0, 1, 1)
        self.C3 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.C3.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.C3.setObjectName("C3")
        self.gridLayout_4.addWidget(self.C3, 3, 0, 1, 1)
        self.L2_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.L2_2.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.L2_2.setObjectName("L2_2")
        self.gridLayout_4.addWidget(self.L2_2, 2, 2, 1, 1)
        self.S1 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.S1.setObjectName("S1")
        self.gridLayout_4.addWidget(self.S1, 0, 3, 1, 1)
        self.S4 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.S4.setObjectName("S4")
        self.gridLayout_4.addWidget(self.S4, 5, 3, 1, 1)
        self.C5 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.C5.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.C5.setObjectName("C5")
        self.gridLayout_4.addWidget(self.C5, 6, 0, 1, 1)
        self.L5 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.L5.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.L5.setObjectName("L5")
        self.gridLayout_4.addWidget(self.L5, 6, 2, 1, 1)
        self.S4_3 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.S4_3.setObjectName("S4_3")
        self.gridLayout_4.addWidget(self.S4_3, 6, 3, 1, 1)
        self.S2 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.S2.setObjectName("S2")
        self.gridLayout_4.addWidget(self.S2, 2, 3, 1, 1)
        self.L3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.L3.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.L3.setObjectName("L3")
        self.gridLayout_4.addWidget(self.L3, 3, 2, 1, 1)
        self.S3 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.S3.setObjectName("S3")
        self.gridLayout_4.addWidget(self.S3, 3, 3, 1, 1)
        self.C2 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.C2.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.C2.setObjectName("C2")
        self.gridLayout_4.addWidget(self.C2, 2, 0, 1, 1)
        self.L4 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.L4.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.L4.setObjectName("L4")
        self.gridLayout_4.addWidget(self.L4, 5, 2, 1, 1)
        self.C1 = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.C1.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.C1.setObjectName("C1")
        self.gridLayout_4.addWidget(self.C1, 0, 0, 1, 1)
        self.L1_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.L1_2.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.L1_2.setObjectName("L1_2")
        self.gridLayout_4.addWidget(self.L1_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(490, 150, 231, 31))
        self.label_3.setStyleSheet("color:rgb(243, 243, 243);font: 87 italic 11pt \"Segoe UI Black\";\n"
"font: 87 italic 22pt \"Segoe UI Black\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(410, 190, 385, 161))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.L10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.L10.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.L10.setObjectName("L10")
        self.gridLayout_3.addWidget(self.L10, 2, 2, 1, 1)
        self.C10 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.C10.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.C10.setObjectName("C10")
        self.gridLayout_3.addWidget(self.C10, 2, 0, 1, 1)
        self.S10 = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.S10.setObjectName("S10")
        self.gridLayout_3.addWidget(self.S10, 2, 4, 1, 1)
        self.C12 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.C12.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.C12.setObjectName("C12")
        self.gridLayout_3.addWidget(self.C12, 5, 0, 1, 1)
        self.C9 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.C9.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.C9.setObjectName("C9")
        self.gridLayout_3.addWidget(self.C9, 0, 0, 1, 1)
        self.S9 = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.S9.setObjectName("S9")
        self.gridLayout_3.addWidget(self.S9, 0, 4, 1, 1)
        self.S12 = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.S12.setObjectName("S12")
        self.gridLayout_3.addWidget(self.S12, 5, 4, 1, 1)
        self.L9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.L9.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.L9.setObjectName("L9")
        self.gridLayout_3.addWidget(self.L9, 0, 2, 1, 1)
        self.S11 = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.S11.setObjectName("S11")
        self.gridLayout_3.addWidget(self.S11, 3, 4, 1, 1)
        self.L11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.L11.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.L11.setObjectName("L11")
        self.gridLayout_3.addWidget(self.L11, 3, 2, 1, 1)
        self.C11 = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.C11.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.C11.setObjectName("C11")
        self.gridLayout_3.addWidget(self.C11, 3, 0, 1, 1)
        self.L12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.L12.setStyleSheet("color:rgb(0, 0, 0);font: 10pt \"Stencil\";\n"
"font: 10pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(255, 255, 255);")
        self.L12.setObjectName("L12")
        self.gridLayout_3.addWidget(self.L12, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 841, 621))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/cfe0b6eeee6828d4d804424e7919184d.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.L1.raise_()
        self.take_order_button.raise_()
        self.formLayoutWidget.raise_()
        self.label_2.raise_()
        self.L2.raise_()
        self.label_4.raise_()
        self.gridLayoutWidget.raise_()
        self.B2.raise_()
        self.gridLayoutWidget_4.raise_()
        self.label_3.raise_()
        self.gridLayoutWidget_3.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.L1.setText(_translate("Dialog", "Greek  Burger"))
        self.take_order_button.setText(_translate("Dialog", "Take Order"))
        self.P3.setText(_translate("Dialog", "VAT"))
        self.P2_2.setText(_translate("Dialog", "BILL"))
        self.P4.setText(_translate("Dialog", "TOTAL"))
        self.label_2.setText(_translate("Dialog", "Burger"))
        self.L2.setText(_translate("Dialog", "Menu"))
        self.label_4.setText(_translate("Dialog", "Fries"))
        self.L7.setText(_translate("Dialog", "₦1000"))
        self.L8.setText(_translate("Dialog", "₦1000"))
        self.L6.setText(_translate("Dialog", "₦1000"))
        self.C6.setText(_translate("Dialog", "French Fries"))
        self.C7.setText(_translate("Dialog", "Yam Fries"))
        self.C8.setText(_translate("Dialog", "Masala Fries"))
        self.B2.setText(_translate("Dialog", "Submit"))
        self.C4.setText(_translate("Dialog", "Cheese Burger"))
        self.C3.setText(_translate("Dialog", "Chimango Burger"))
        self.L2_2.setText(_translate("Dialog", "₦7000"))
        self.C5.setText(_translate("Dialog", "Beef Burger"))
        self.L5.setText(_translate("Dialog", "₦7000"))
        self.L3.setText(_translate("Dialog", "₦7000"))
        self.C2.setText(_translate("Dialog", "Chicken Burger"))
        self.L4.setText(_translate("Dialog", "₦7000"))
        self.C1.setText(_translate("Dialog", "Gringo Burger"))
        self.L1_2.setText(_translate("Dialog", "₦7000"))
        self.label_3.setText(_translate("Dialog", "Milkshakes"))
        self.L10.setText(_translate("Dialog", "₦4000"))
        self.C10.setText(_translate("Dialog", "Oreos Milkshake"))
        self.C12.setText(_translate("Dialog", "Strawberry Milkshake"))
        self.C9.setText(_translate("Dialog", "Banana Milkshake"))
        self.L9.setText(_translate("Dialog", "₦3500"))
        self.L11.setText(_translate("Dialog", "₦3500"))
        self.C11.setText(_translate("Dialog", "Vanilla Milkshake"))
        self.L12.setText(_translate("Dialog", "₦3500"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
